on: [push, pull_request]

jobs:
  job:
    runs-on: ubuntu-latest
    name: Is Palindrome Function
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: seperate action step
        uses: ./ # Uses an action in the root directory
